### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyr3ne** [lordvaida/bwa-u4-feature-request#1]
**Grade:  Meets expectations**

**Summary:**  

I love the detail with which you explained your concept. 

You lay out a rock solid plan for implementing a feature that definitely improves the user’s Jammming experience. The idea itself is a natural suggestion, as most users would likely assume the Enter key would serve that purpose and therefore would find it inconvenient that the app doesn’t do that. Your implementation is also the easiest way to accomplish the goal. 

I thought the technical design was outstanding with and detailed instructions on implementation. Caveats were well thought out. Nice work! 

I was thinking you don't need to remove the search button altogether. They could have the option to click or press enter for that. But the search button can look a bit redundant.  The usage should become apparent as they use the search function.

**Comment by lordvaida** [comment]
Thanks! Good point about the search button.
